---

- name: template file1 to the machine (service3)
  ansible.builtin.template:
    src: file1.j2
    dest: /etc/file1_service3.txt

- name: template file2 to the machine (service3)
  ansible.builtin.template:
    src: file2.j2
    dest: /etc/file2_service3.txt

- name: template file3 to the machine (service3)
  ansible.builtin.template:
    src: file3.j2
    dest: /etc/file3_service3.txt


